### ISSUE TITLE
Add support for `default` in parameter definitions

### ISSUE THREAD

**Issue by kevinawoo** [luxe-eng/koa-spec#49]
Swagger supports the `default` keyword for paramaters, items, headers, and schema.

See: http://swagger.io/unlocking-the-spec-the-default-keyword/

**Comment by nicolasgramlich** [comment]
Imo: Let's focus on adding the support to parameters/attributes first, since that's what the main support is focused on right now. @kevinawoo sounds good?

**Comment by kevinawoo** [comment]
Sounds good to me.

**Comment by SylvainEstevez** [comment]
- Added tests for booleans coercion
- Added ability to have defaults in querystring
